export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIE = "GET_MOVIE";
export const GET_GENRE_MOVIE = "GET_GENRE_MOVIE";
export const GET_MOVIE_DISCOVER = "GET_MOVIE_DISCOVER";
export const GET_MOVIE_COLLECTION = "GET_MOVIE_COLLECTION";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
